[build]
  command = "npm rebuild sharp --foreground-scripts && npx gatsby clean && npx gatsby build"
  publish = "public"

[build.environment]
  NODE_VERSION = "18.20.8"
  NPM_VERSION = "9.5.1"
  NVM_VERSION = "1.1.9"
  NPM_FLAGS = "--legacy-peer-deps --ignore-scripts"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200